// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementSystem.Context;

#nullable disable

namespace TaskManagementSystem.Migrations
{
    [DbContext(typeof(TaskManagementDbContext))]
    partial class TaskManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementSystem.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("ToDo");

                    b.Property<DateTime>("TaskCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByAdminId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            AssignedUserId = 3,
                            CreatedByAdminId = 1,
                            Description = "Yeni proje için teknik dokümantasyon hazırlanacak",
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 1, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Proje Dokümantasyonu Hazırlama"
                        },
                        new
                        {
                            TaskId = 2,
                            AssignedUserId = 4,
                            CreatedByAdminId = 1,
                            Description = "MySQL veritabanı şeması oluşturulacak",
                            DueDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Done",
                            TaskCreatedAt = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Veritabanı Tasarımı"
                        },
                        new
                        {
                            TaskId = 3,
                            AssignedUserId = 5,
                            CreatedByAdminId = 2,
                            Description = "RESTful API endpoint'leri geliştirilecek",
                            DueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 1, 22, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "API Endpoint Geliştirme"
                        },
                        new
                        {
                            TaskId = 4,
                            AssignedUserId = 6,
                            CreatedByAdminId = 1,
                            Description = "Next.js ile backend entegrasyonu yapılacak",
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 1, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Frontend Entegrasyonu"
                        },
                        new
                        {
                            TaskId = 5,
                            AssignedUserId = 7,
                            CreatedByAdminId = 2,
                            Description = "Unit ve integration testler yazılacak",
                            DueDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 1, 26, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Test Senaryoları Yazma"
                        },
                        new
                        {
                            TaskId = 6,
                            AssignedUserId = 8,
                            CreatedByAdminId = 1,
                            Description = "Dashboard için grafik bileşenleri eklenecek",
                            DueDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 1, 27, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chart.js Entegrasyonu"
                        },
                        new
                        {
                            TaskId = 7,
                            AssignedUserId = 3,
                            CreatedByAdminId = 2,
                            Description = "Kimlik doğrulama sistemi kurulacak",
                            DueDate = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Done",
                            TaskCreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "JWT Authentication"
                        },
                        new
                        {
                            TaskId = 8,
                            AssignedUserId = 9,
                            CreatedByAdminId = 1,
                            Description = "OpenXML ile rapor export fonksiyonu eklenecek",
                            DueDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 1, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Excel Export Özelliği"
                        },
                        new
                        {
                            TaskId = 9,
                            AssignedUserId = 10,
                            CreatedByAdminId = 2,
                            Description = "Kullanıcılara email gönderme servisi",
                            DueDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 1, 29, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Email Bildirimi Sistemi"
                        },
                        new
                        {
                            TaskId = 10,
                            AssignedUserId = 11,
                            CreatedByAdminId = 1,
                            Description = "Kullanıcı bilgilerini görüntüleme ve düzenleme",
                            DueDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Done",
                            TaskCreatedAt = new DateTime(2026, 1, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kullanıcı Profil Sayfası"
                        },
                        new
                        {
                            TaskId = 11,
                            AssignedUserId = 12,
                            CreatedByAdminId = 2,
                            Description = "Admin ve kullanıcı rollerini yönetme",
                            DueDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 1, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rol Yönetim Sistemi"
                        },
                        new
                        {
                            TaskId = 12,
                            AssignedUserId = 3,
                            CreatedByAdminId = 1,
                            Description = "Ana sayfa dashboard bileşenleri",
                            DueDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 1, 21, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dashboard Tasarımı"
                        },
                        new
                        {
                            TaskId = 13,
                            AssignedUserId = 4,
                            CreatedByAdminId = 2,
                            Description = "Veritabanı sorgu optimizasyonları",
                            DueDate = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 1, 31, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "Performans Optimizasyonu"
                        },
                        new
                        {
                            TaskId = 14,
                            AssignedUserId = 5,
                            CreatedByAdminId = 1,
                            Description = "Penetrasyon testleri ve güvenlik analizi",
                            DueDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 1, 23, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            Title = "Güvenlik Testleri"
                        },
                        new
                        {
                            TaskId = 15,
                            AssignedUserId = 6,
                            CreatedByAdminId = 2,
                            Description = "Mobil cihazlar için responsive tasarım",
                            DueDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Done",
                            TaskCreatedAt = new DateTime(2026, 1, 17, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mobil Responsive Tasarım"
                        },
                        new
                        {
                            TaskId = 16,
                            AssignedUserId = 7,
                            CreatedByAdminId = 1,
                            Description = "Gelişmiş arama ve filtreleme özellikleri",
                            DueDate = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 2, 1, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Arama ve Filtreleme"
                        },
                        new
                        {
                            TaskId = 17,
                            AssignedUserId = 8,
                            CreatedByAdminId = 2,
                            Description = "Kullanıcı bildirim ayarları",
                            DueDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 2, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bildirim Tercihleri"
                        },
                        new
                        {
                            TaskId = 18,
                            AssignedUserId = 9,
                            CreatedByAdminId = 1,
                            Description = "Otomatik veri yedekleme mekanizması",
                            DueDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 2, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Veri Yedekleme Sistemi"
                        },
                        new
                        {
                            TaskId = 19,
                            AssignedUserId = 10,
                            CreatedByAdminId = 2,
                            Description = "Swagger/OpenAPI dokümantasyonu",
                            DueDate = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Done",
                            TaskCreatedAt = new DateTime(2026, 1, 19, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "API Dokümantasyonu"
                        },
                        new
                        {
                            TaskId = 20,
                            AssignedUserId = 11,
                            CreatedByAdminId = 1,
                            Description = "Merkezi loglama ve hata takibi",
                            DueDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 2, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Loglama Sistemi"
                        },
                        new
                        {
                            TaskId = 21,
                            AssignedUserId = 12,
                            CreatedByAdminId = 2,
                            Description = "2FA güvenlik katmanı ekleme",
                            DueDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 2, 5, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Title = "İki Faktörlü Doğrulama"
                        },
                        new
                        {
                            TaskId = 22,
                            AssignedUserId = 3,
                            CreatedByAdminId = 1,
                            Description = "API rate limiting implementasyonu",
                            DueDate = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 2, 6, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rate Limiting"
                        },
                        new
                        {
                            TaskId = 23,
                            AssignedUserId = 4,
                            CreatedByAdminId = 2,
                            Description = "i18n entegrasyonu (TR, EN)",
                            DueDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "ToDo",
                            TaskCreatedAt = new DateTime(2026, 2, 7, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Çoklu Dil Desteği"
                        },
                        new
                        {
                            TaskId = 24,
                            AssignedUserId = 5,
                            CreatedByAdminId = 1,
                            Description = "Dosya upload ve depolama sistemi",
                            DueDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Done",
                            TaskCreatedAt = new DateTime(2026, 1, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dosya Yükleme Servisi"
                        },
                        new
                        {
                            TaskId = 25,
                            AssignedUserId = 6,
                            CreatedByAdminId = 2,
                            Description = "Redis ile caching implementasyonu",
                            DueDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            TaskCreatedAt = new DateTime(2026, 2, 8, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cache Mekanizması"
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UserCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@company.com",
                            Name = "Saliha",
                            PasswordHash = "admin123",
                            RoleId = 0,
                            Surname = "Ünersoy",
                            UserCreatedAt = new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            Email = "admin2@company.com",
                            Name = "Admin",
                            PasswordHash = "admin123",
                            RoleId = 0,
                            Surname = "Şen",
                            UserCreatedAt = new DateTime(2026, 1, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            Email = "ahmet.yilmaz@company.com",
                            Name = "Ahmet",
                            PasswordHash = "ahmet123",
                            RoleId = 1,
                            Surname = "Yılmaz",
                            UserCreatedAt = new DateTime(2026, 1, 5, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 4,
                            Email = "ayse.kaya@company.com",
                            Name = "Ayşe",
                            PasswordHash = "ayse123",
                            RoleId = 1,
                            Surname = "Kaya",
                            UserCreatedAt = new DateTime(2026, 1, 6, 10, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 5,
                            Email = "mehmet.demir@company.com",
                            Name = "Mehmet",
                            PasswordHash = "$2a$11$cD3eF4gH5iJ6kL7mN8oP9qR0sT1uV2wX3yZ4aB5C",
                            RoleId = 1,
                            Surname = "Demir",
                            UserCreatedAt = new DateTime(2026, 1, 7, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 6,
                            Email = "fatma.sahin@company.com",
                            Name = "Fatma",
                            PasswordHash = "$2a$11$dE4fG5hI6jK7lM8nO9pQ0rS1tU2vW3xY4zA5bC6D",
                            RoleId = 1,
                            Surname = "Şahin",
                            UserCreatedAt = new DateTime(2026, 1, 8, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 7,
                            Email = "ali.celik@company.com",
                            Name = "Ali",
                            PasswordHash = "$2a$11$eF5gH6iJ7kL8mN9oP0qR1sT2uV3wX4yZ5aB6cD7E",
                            RoleId = 1,
                            Surname = "Çelik",
                            UserCreatedAt = new DateTime(2026, 1, 9, 8, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 8,
                            Email = "zeynep.aydin@company.com",
                            Name = "Zeynep",
                            PasswordHash = "$2a$11$fG6hI7jK8lM9nO0pQ1rS2tU3vW4xY5zA6bC7dE8F",
                            RoleId = 1,
                            Surname = "Aydın",
                            UserCreatedAt = new DateTime(2026, 1, 10, 13, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 9,
                            Email = "mustafa.koc@company.com",
                            Name = "Mustafa",
                            PasswordHash = "$2a$11$gH7iJ8kL9mN0oP1qR2sT3uV4wX5yZ6aB7cD8eF9G",
                            RoleId = 1,
                            Surname = "Koç",
                            UserCreatedAt = new DateTime(2026, 1, 11, 15, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 10,
                            Email = "elif.arslan@company.com",
                            Name = "Elif",
                            PasswordHash = "$2a$11$hI8jK9lM0nO1pQ2rS3tU4vW5xY6zA7bC8dE9fG0H",
                            RoleId = 1,
                            Surname = "Arslan",
                            UserCreatedAt = new DateTime(2026, 1, 12, 9, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 11,
                            Email = "can.ozturk@company.com",
                            Name = "Can",
                            PasswordHash = "$2a$11$iJ9kL0mN1oP2qR3sT4uV5wX6yZ7aB8cD9eF0gH1I",
                            RoleId = 1,
                            Surname = "Öztürk",
                            UserCreatedAt = new DateTime(2026, 1, 13, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 12,
                            Email = "selin.kurt@company.com",
                            Name = "Selin",
                            PasswordHash = "$2a$11$jK0lM1nO2pQ3rS4tU5vW6xY7zA8bC9dE0fG1hI2J",
                            RoleId = 1,
                            Surname = "Kurt",
                            UserCreatedAt = new DateTime(2026, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TaskManagementSystem.Models.Task", b =>
                {
                    b.HasOne("TaskManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManagementSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
